source 'https://rubygems.org' 

gem 'sinatra'
gem 'sinatra-asset-pipeline'
gem 'puma'
gem 'bson_ext'
gem 'mongo'
gem 'json'
gem 'activesupport-inflector'
gem 'i18n'
gem 'pry'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-github'
gem 'omniauth-twitter'
gem 'omniauth-facebook'

